### ISSUE TITLE
fish: Unknown command: pinterest.py

### ISSUE THREAD

**Issue by yrt05** [SevenLines/pinterest-board-downloader#1]
how to use your script?

**Comment by SevenLines** [comment]
you can eitheir install it as package and run pinterest command, or run it manually from src like
```
python src/__init__.py username
```

**Comment by yrt05** [comment]
python: can't open file 'src/__init__.py': [Errno 2] No such file or directory
(manjaro kde)

**Comment by yrt05** [comment]
dont worked (manjaro kde)
